None

        ptimizer = torch.optim.RMSprop(model.parameters(), lr=0.00001, alpha=0.99, eps=1e-08, weight_decay=0.0001, momentum=0.9, centered=True)
        scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.0001, max_lr=0.01)



        max_epoch = 300
        validation = 60


    
MONAI version: 1.2.0rc7+9.g84940298
Numpy version: 1.24.2
Pytorch version: 1.13.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 84940298bff9ff1f54845eb8ae7422c0092c09c1
MONAI __file__: /home/guest185/hackathon_38/lib/python3.8/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.2
ITK version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 5.1.0
scikit-image version: 0.19.3
Pillow version: 9.5.0
Tensorboard version: 2.13.0
gdown version: 4.7.1
TorchVision version: 0.14.1
tqdm version: 4.65.0
lmdb version: 1.2.1
psutil version: 5.9.4
pandas version: 1.5.3
einops version: 0.6.1
transformers version: 4.21.3
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: 1.0.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

/tmp/tmpgyzyt8nx
image shape: (240, 240, 155), label shape: (240, 240, 155)
Sun Aug  6 23:00:52 2023 Epoch: 0
In the future `np.bool` will be defined as the corresponding NumPy scalar.
In the future `np.bool` will be defined as the corresponding NumPy scalar.
In the future `np.bool` will be defined as the corresponding NumPy scalar.
In the future `np.bool` will be defined as the corresponding NumPy scalar.
monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
In the future `np.bool` will be defined as the corresponding NumPy scalar.
In the future `np.bool` will be defined as the corresponding NumPy scalar.
Traceback (most recent call last):
  File "ssa_swin_model.py", line 421, in <module>
    ) = trainer(
  File "ssa_swin_model.py", line 342, in trainer
    train_loss = train_epoch(
  File "ssa_swin_model.py", line 254, in train_epoch
    for idx, batch_data in enumerate(loader):
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/transform.py", line 103, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/transform.py", line 67, in _apply_transform
    return transform(parameters)
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/intensity/array.py", line 591, in __call__
    self.randomize(img_size=img.shape[1:])
AttributeError: 'dict' object has no attribute 'shape'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/transform.py", line 103, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/transform.py", line 67, in _apply_transform
    return transform(parameters)
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/compose.py", line 451, in __call__
    return execute_compose(
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/compose.py", line 199, in execute_compose
    data = apply_transform(_transform, data, map_items, unpack_items, log_stats)
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/transform.py", line 130, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.intensity.array.RandBiasField object at 0x2b1a47a0e040>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/data/dataset.py", line 109, in __getitem__
    return self._transform(index)
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/data/dataset.py", line 95, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/guest185/hackathon_38/lib/python3.8/site-packages/monai/transforms/transform.py", line 130, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x2b1a47a0ed60>

